//! Generate the cross-environment endpoint registry from
//! `environments.json` — the single source of truth for every
//! per-(env, key) service URL.
//!
//! The registry file lives in THIS crate (`folddb_profile/environments.json`).
//! It moved here from the deleted `fold_db_node` crate in the Mini-only
//! cutover (2026-07-12; restore point: branch `archive/desktop-dmg-pre-removal`).
//! The generated module is `include!()`d by `src/endpoints.rs`, and
//! `scripts/lints/lint-no-hardcoded-urls.sh` enforces that no gateway
//! hostname appears anywhere else.
//!
//! A malformed registry breaks the build, which is the point — drift
//! cannot reach a release.

use std::path::Path;

const ENVIRONMENTS_JSON: &str = "environments.json";

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={ENVIRONMENTS_JSON}");
    generate_environments_module();
}

/// Parse `environments.json` and emit `$OUT_DIR/environments_generated.rs`
/// with one `pub const` per (env, key). Keep the generated names in
/// lockstep with `endpoints.rs`: any new key in the JSON automatically
/// gets a constant, but the consumer-side wrapper must opt in by
/// referencing it.
fn generate_environments_module() {
    let path = Path::new(ENVIRONMENTS_JSON);
    let raw = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("environments.json must exist at {ENVIRONMENTS_JSON}: {e}"));

    let envs = ["dev", "prod"];
    // `region` is in environments.json but only consumed by shell helpers
    // (now retired with the desktop node) via jq — no Rust caller reads it. Skip it
    // here so the generated module has no dead constants.
    let keys = ["exemem_api", "schema_service", "portal"];

    let mut out = String::from(
        "// @generated by build.rs from environments.json — do not edit.\n\
         // Edits to URLs go in environments.json (the single source of truth).\n\n",
    );
    for env in &envs {
        for key in &keys {
            let value = extract_string(&raw, env, key)
                .unwrap_or_else(|| panic!("environments.json: missing environments.{env}.{key}"));
            let const_name = format!("{}_{}", env.to_uppercase(), key.to_uppercase());
            out.push_str(&format!("pub const {const_name}: &str = {value:?};\n"));
        }
    }

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
    let out_path = Path::new(&out_dir).join("environments_generated.rs");
    std::fs::write(&out_path, out)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", out_path.display()));
}

/// Tiny JSON-string extractor for the fixed shape
/// `{"environments": {"<env>": {"<key>": "<value>", ...}, ...}}`. Avoids a
/// `serde_json` build-dep — at build time we'd rather not compile serde
/// just to read four URLs. Robust to whitespace and field ordering; not
/// robust to escaped quotes inside values (we don't have any).
fn extract_string(raw: &str, env: &str, key: &str) -> Option<String> {
    // Find `"<env>":` then within its object find `"<key>":`. Brace-depth
    // tracking keeps us inside the right env's object.
    let env_marker = format!("\"{env}\"");
    let env_start = raw.find(&env_marker)?;
    let after_env = &raw[env_start..];
    let obj_start = after_env.find('{')?;
    let mut depth = 0i32;
    let mut obj_end = obj_start;
    for (i, c) in after_env[obj_start..].char_indices() {
        match c {
            '{' => depth += 1,
            '}' => {
                depth -= 1;
                if depth == 0 {
                    obj_end = obj_start + i;
                    break;
                }
            }
            _ => {}
        }
    }
    let env_obj = &after_env[obj_start..=obj_end];

    let key_marker = format!("\"{key}\"");
    let key_pos = env_obj.find(&key_marker)?;
    let after_key = &env_obj[key_pos + key_marker.len()..];
    let colon = after_key.find(':')?;
    let after_colon = &after_key[colon + 1..];
    let q1 = after_colon.find('"')?;
    let after_q1 = &after_colon[q1 + 1..];
    let q2 = after_q1.find('"')?;
    Some(after_q1[..q2].to_string())
}
