//! Schema.org starter-seed loader.
//!
//! **Not live language** (Tom 2026-08-17,
//! `preference-schema-org-not-live-language`). [`seed`] is a documented
//! no-op so cold start cannot re-insert the dump.
//!
//! The JSON snapshots stay in git. They are compiled into this crate
//! only with the `schema-org-seed-data` feature (offline generators and
//! dump-parse tests). The Lambda crate must not enable that feature.
//!
//! Historically, at cold start [`seed`] loaded two **pre-validated JSON
//! snapshots** committed to the repo and inserted them into the schema
//! service with no parsing, no semantic matching, and no classification
//! work:
//!
//! - [`VALIDATED_CANONICAL_FIELDS_JSON`] — one aggregate file containing
//!   every canonical field (curated + Schema.org-derived), with
//!   descriptions, types, classifications, and interest categories
//!   already baked in by the generator.
//! - [`VALIDATED_SCHEMAS_DIR`] — one file per Schema.org class under
//!   `data/schema_org/schemas/*.json`, embedded at build time via
//!   `include_dir!`. Schemas are already post-validation:
//!   `identity_hash` computed, `descriptive_name` canonicalized,
//!   `field_data_classifications` propagated.
//!
//! Both snapshots are produced by the one-shot generator at
//! `schema_service/scripts/generate_validated_schema_org_seeds`. It
//! parses the Schema.org JSON-LD dump, applies the hand-curated
//! classification overlay from
//! `schema_service/scripts/generate_schema_org_classifications`, runs
//! every class serially through [`SchemaServiceState::add_schema`] using
//! the real fastembed embedder, and dumps the final state. Regenerate by
//! running the binary and committing the JSON diff.
//!
//! Why this split: the expensive work (fastembed-based semantic
//! canonicalization, classification propagation) happens once at dev
//! time. Cold start is then a deterministic JSON-read pass, not a
//! pipeline re-run.
//!
//! ## Parsing utilities
//!
//! This module also exposes [`parse_dump`] and
//! [`property_name_to_snake_case`] — used exclusively by the two
//! offline generators. The runtime loader does not touch the JSON-LD
//! dump. The committed `schemaorg-current-https.jsonld` file remains
//! embedded so generators can read it, and the classification overlay
//! is embedded so the overlay-seeding path used by the validated-seeds
//! generator still works.

#[cfg(feature = "schema-org-seed-data")]
use std::collections::{HashMap, HashSet};
#[cfg(feature = "schema-org-seed-data")]
use std::sync::OnceLock;

#[cfg(feature = "schema-org-seed-data")]
use schema_types::DataClassification;
#[cfg(any(test, feature = "schema-org-seed-data"))]
use schema_types::FieldValueType;
#[cfg(feature = "schema-org-seed-data")]
use schema_types::FoldDbError;
use schema_types::FoldDbResult;
#[cfg(feature = "schema-org-seed-data")]
use schema_types::Schema;
#[cfg(feature = "schema-org-seed-data")]
use serde::Deserialize;

use crate::state::SchemaServiceState;
#[cfg(feature = "schema-org-seed-data")]
use crate::types::CanonicalField;

/// The committed Schema.org JSON-LD dump.
#[cfg(feature = "schema-org-seed-data")]
const SCHEMA_ORG_JSONLD: &str = include_str!("../data/schema_org/schemaorg-current-https.jsonld");

/// Pre-computed classification overlay for Schema.org properties.
///
/// Generated by the standalone binary
/// `schema_service/scripts/generate_schema_org_classifications`
/// (see its README/main docs). The file is committed to the repo so the
/// service doesn't run clustering logic at cold start — it just looks up
/// each property in this pre-built map.
///
/// Regenerate by running the generator and committing the diff.
#[cfg(feature = "schema-org-seed-data")]
const SCHEMA_ORG_CLASSIFICATION_OVERLAY: &str =
    include_str!("../data/schema_org/classification_overlay.json");

/// Structure of one entry in the classification overlay JSON.
///
/// The generator emits these with explicit serde field names; we parse
/// them into a static map at first use. The `cluster` key on disk is
/// retained for human readability of the committed overlay and is
/// ignored here by serde.
#[cfg(feature = "schema-org-seed-data")]
#[derive(Debug, Clone, Deserialize)]
struct OverlayEntry {
    sensitivity_level: u8,
    data_domain: String,
    #[serde(default)]
    interest_category: Option<String>,
}

/// Envelope of the committed classification overlay. The `version` and
/// `generated_at` / `source_file` / `generator` keys on disk are
/// informational only and ignored by serde.
#[cfg(feature = "schema-org-seed-data")]
#[derive(Debug, Deserialize)]
struct OverlayDocument {
    fields: HashMap<String, OverlayEntry>,
}

/// Parse the committed overlay once per process and cache it.
///
/// Returns a reference to a map keyed on snake_case property name.
#[cfg(feature = "schema-org-seed-data")]
fn overlay_map() -> &'static HashMap<String, OverlayEntry> {
    static OVERLAY: OnceLock<HashMap<String, OverlayEntry>> = OnceLock::new();
    OVERLAY.get_or_init(|| {
        // Panic at initialization rather than returning an error: if the
        // overlay file is malformed, the service would boot with every
        // Schema.org field at the fail-closed baseline, which masks the
        // bug. Better to crash loudly at startup so the deploy fails
        // visibly.
        let doc: OverlayDocument = serde_json::from_str(SCHEMA_ORG_CLASSIFICATION_OVERLAY)
            .unwrap_or_else(|e| {
                panic!(
                    "Failed to parse committed Schema.org classification overlay: {e}. \
                     Regenerate via `cargo run --bin generate-schema-org-classifications` \
                     and commit the fixed file."
                )
            });
        doc.fields
    })
}

/// Look up the classification for a Schema.org property by snake_case
/// name. Returns the overlay entry if present; otherwise constructs a
/// fail-closed baseline entry (`sensitivity=4, domain="general"`). The
/// runtime path never makes a classification decision beyond this
/// fallback — the overlay is the authoritative hand-curated answer.
#[cfg(feature = "schema-org-seed-data")]
fn classify_schema_org_field(
    snake_name: &str,
) -> FoldDbResult<(DataClassification, Option<String>)> {
    let map = overlay_map();
    let (sensitivity, domain, interest) = match map.get(snake_name) {
        Some(entry) => (
            entry.sensitivity_level,
            entry.data_domain.as_str(),
            entry.interest_category.clone(),
        ),
        None => (4, "general", None),
    };
    let classification = DataClassification::new(sensitivity, domain).map_err(|e| {
        FoldDbError::Config(format!(
            "Invalid overlay classification for Schema.org property '{snake_name}' \
             (sensitivity={sensitivity}, domain='{domain}'): {e}"
        ))
    })?;
    Ok((classification, interest))
}

/// Committed validated canonical-fields aggregate. Emitted by
/// `generate_validated_schema_org_seeds` — one entry per property, with
/// the classification already applied.
#[cfg(feature = "schema-org-seed-data")]
const VALIDATED_CANONICAL_FIELDS_JSON: &str =
    include_str!("../data/schema_org/validated_canonical_fields.json");

/// Committed per-schema files under `data/schema_org/schemas/*.json`.
/// `include_dir!` embeds the whole directory at build time so cold start
/// needs no filesystem I/O.
#[cfg(feature = "schema-org-seed-data")]
static VALIDATED_SCHEMAS_DIR: include_dir::Dir<'_> =
    include_dir::include_dir!("$CARGO_MANIFEST_DIR/data/schema_org/schemas");

/// Envelope shape of the committed canonical-fields aggregate. The
/// `version` and generator-metadata keys on disk are informational and
/// ignored by serde.
#[cfg(feature = "schema-org-seed-data")]
#[derive(Deserialize)]
struct ValidatedCanonicalFieldsDoc {
    entries: HashMap<String, CanonicalField>,
}

/// Cold-start hook. **Does not insert Schema.org types or properties.**
///
/// The live language is the curated builtin field catalog plus
/// `system_seed` / user / `owner_app_id=templates` schemas. Call
/// [`load_validated_canonical_fields`] / [`load_validated_schemas`]
/// only from the offline generator or from tests that assert the
/// committed dump still parses.
pub fn seed(_state: &SchemaServiceState) -> FoldDbResult<()> {
    tracing::info!(
        target: "schema_service::schema",
        "Skipping Schema.org starter seed (not live language)"
    );
    Ok(())
}

/// Load the aggregate canonical-fields JSON into the in-memory registry.
/// Classification travels with each entry from the committed JSON; no
/// runtime clustering, no LLM calls, no S3 writes, no embedding. The
/// warm-embeddings admin endpoint is responsible for populating
/// similarity-lookup embeddings afterward.
#[cfg(feature = "schema-org-seed-data")]
pub fn load_validated_canonical_fields(state: &SchemaServiceState) -> FoldDbResult<()> {
    let doc: ValidatedCanonicalFieldsDoc = serde_json::from_str(VALIDATED_CANONICAL_FIELDS_JSON)
        .map_err(|e| {
            FoldDbError::Config(format!(
                "Failed to parse committed validated_canonical_fields.json: {e}. \
                 Regenerate via `cargo run --release --bin generate-validated-schema-org-seeds`."
            ))
        })?;

    let total = doc.entries.len();
    for (name, canonical) in doc.entries {
        state.insert_pre_validated_canonical_field(&name, canonical);
    }

    tracing::info!(
            target: "schema_service::schema",
        "Loaded {} validated Schema.org canonical fields from JSON (in-memory only)",
        total
    );
    Ok(())
}

/// Load every committed per-schema JSON file under
/// `data/schema_org/schemas/` into the registry via
/// [`SchemaServiceState::insert_pre_validated_schema`] — no re-validation,
/// no semantic matching, no classification propagation.
#[cfg(feature = "schema-org-seed-data")]
pub fn load_validated_schemas(state: &SchemaServiceState) -> FoldDbResult<()> {
    let mut loaded = 0usize;
    let mut skipped_non_files = 0usize;

    for file in VALIDATED_SCHEMAS_DIR.files() {
        let path = file.path().display().to_string();
        let contents = file.contents_utf8().ok_or_else(|| {
            FoldDbError::Config(format!("Validated schema file '{path}' is not valid UTF-8"))
        })?;

        // Tolerate unexpected non-.json files in the directory rather
        // than crashing the service — if someone accidentally commits a
        // README or editor swap file, log and skip.
        if !path.ends_with(".json") {
            skipped_non_files += 1;
            continue;
        }

        let mut schema: Schema = serde_json::from_str(contents).map_err(|e| {
            FoldDbError::Config(format!(
                "Failed to parse committed validated schema file '{path}': {e}. \
                 Regenerate via `cargo run --release --bin generate-validated-schema-org-seeds`."
            ))
        })?;

        // Phase A of dual-signal canonicalization defaults `purpose_statement`
        // to `descriptive_name` for user-source schemas in `add_schema`. The
        // committed starter-seed JSON files predate that field and omit it, so
        // apply the same default here before insertion — otherwise the dual-
        // signal gate has no purpose embedding to compare against on the 914
        // StarterSeed schemas.
        if schema
            .purpose_statement
            .as_deref()
            .is_none_or(|p| p.trim().is_empty())
        {
            if let Some(desc) = schema.descriptive_name.as_ref() {
                if !desc.trim().is_empty() {
                    schema.purpose_statement = Some(desc.clone());
                }
            }
        }

        state.insert_pre_validated_schema(&schema)?;
        loaded += 1;
    }

    tracing::info!(
            target: "schema_service::schema",
        "Loaded {} validated Schema.org StarterSeed schemas from JSON (skipped {} non-json entries)",
        loaded,
        skipped_non_files
    );
    Ok(())
}

/// Seed the canonical field registry with every Schema.org property.
#[cfg(feature = "schema-org-seed-data")]
pub async fn seed_canonical_fields(
    state: &SchemaServiceState,
    dump: &ParsedDump,
) -> FoldDbResult<()> {
    let mut count = 0usize;
    for prop in &dump.properties {
        let name = property_name_to_snake_case(&prop.label);
        let description = prop
            .comment
            .as_deref()
            .unwrap_or("(no description)")
            .trim()
            .to_string();
        let field_type = infer_field_type_from_ranges(&prop.range_includes);

        // Pull the classification from the pre-generated overlay. The
        // overlay is hand-curated cluster classifications produced by
        // `schema_service/scripts/generate_schema_org_classifications`
        // and committed as `classification_overlay.json`. Properties the
        // overlay doesn't cover (e.g. a newer Schema.org release that
        // precedes regeneration) fall through to the fail-closed
        // baseline inside `classify_schema_org_field`.
        let (classification, interest_category) = classify_schema_org_field(&name)?;

        let canonical = CanonicalField {
            description,
            field_type,
            version: 1,
            classification: Some(classification),
            interest_category,
        };

        // Idempotent — silently no-ops if name already present (either from
        // the curated builtin list or a prior seed run).
        state.add_canonical_field(&name, canonical).await?;
        count += 1;
    }

    tracing::info!(
            target: "schema_service::schema",
        "Seeded {} Schema.org canonical fields",
        count
    );
    Ok(())
}

// ─────────────────────────────────────────────────────────────────────
//  JSON-LD parsing
//
//  Used by the two offline generators, not by the cold-start seed path.
// ─────────────────────────────────────────────────────────────────────

/// Parsed form of the Schema.org JSON-LD dump, indexed for lookup.
#[cfg(feature = "schema-org-seed-data")]
pub struct ParsedDump {
    pub classes: Vec<SchemaOrgClass>,
    pub properties: Vec<SchemaOrgProperty>,
    /// For each class label, the list of property labels (original
    /// camelCase, not snake_case) whose `domainIncludes` references the
    /// class.
    pub properties_by_domain: HashMap<String, Vec<String>>,
    /// Property lookup by snake_case name for description resolution
    /// during schema construction.
    pub property_by_snake_name: HashMap<String, SchemaOrgProperty>,
}

#[cfg(feature = "schema-org-seed-data")]
#[derive(Debug, Clone)]
pub struct SchemaOrgClass {
    pub label: String,
    pub comment: Option<String>,
}

#[cfg(feature = "schema-org-seed-data")]
#[derive(Debug, Clone)]
pub struct SchemaOrgProperty {
    pub label: String,
    pub comment: Option<String>,
    pub domain_includes: Vec<String>,
    pub range_includes: Vec<String>,
}

#[cfg(feature = "schema-org-seed-data")]
#[derive(Deserialize)]
struct RawDump {
    #[serde(rename = "@graph")]
    graph: Vec<RawNode>,
}

#[cfg(feature = "schema-org-seed-data")]
#[derive(Deserialize)]
struct RawNode {
    #[serde(rename = "@id")]
    id: Option<String>,
    #[serde(rename = "@type")]
    #[serde(default)]
    node_type: OneOrMany<String>,
    #[serde(rename = "rdfs:label")]
    label: Option<LabelField>,
    #[serde(rename = "rdfs:comment")]
    comment: Option<LabelField>,
    #[serde(rename = "schema:domainIncludes")]
    #[serde(default)]
    domain_includes: OneOrMany<RefNode>,
    #[serde(rename = "schema:rangeIncludes")]
    #[serde(default)]
    range_includes: OneOrMany<RefNode>,
}

/// Schema.org JSON-LD uses both single values and arrays for the same
/// fields depending on whether a property applies to one or many types.
/// Collapse both shapes to a Vec.
#[cfg(feature = "schema-org-seed-data")]
#[derive(Deserialize, Default)]
#[serde(untagged)]
enum OneOrMany<T> {
    One(T),
    Many(Vec<T>),
    #[default]
    None,
}

#[cfg(feature = "schema-org-seed-data")]
impl<T> OneOrMany<T> {
    fn into_vec(self) -> Vec<T> {
        match self {
            Self::One(v) => vec![v],
            Self::Many(v) => v,
            Self::None => Vec::new(),
        }
    }
}

#[cfg(feature = "schema-org-seed-data")]
#[derive(Deserialize)]
struct RefNode {
    #[serde(rename = "@id")]
    id: String,
}

/// `rdfs:label` is usually a bare string but occasionally an object with
/// `@value` / `@language`. Accept both.
#[cfg(feature = "schema-org-seed-data")]
#[derive(Deserialize)]
#[serde(untagged)]
enum LabelField {
    Plain(String),
    Tagged {
        #[serde(rename = "@value")]
        value: String,
    },
}

#[cfg(feature = "schema-org-seed-data")]
impl LabelField {
    fn into_string(self) -> String {
        match self {
            Self::Plain(s) => s,
            Self::Tagged { value } => value,
        }
    }
}

/// Parse the embedded Schema.org JSON-LD dump.
///
/// Public so tests can exercise the parse path independently of the seed
/// path.
#[cfg(feature = "schema-org-seed-data")]
pub fn parse_dump() -> FoldDbResult<ParsedDump> {
    let raw: RawDump = serde_json::from_str(SCHEMA_ORG_JSONLD).map_err(|e| {
        FoldDbError::Config(format!("Failed to parse embedded Schema.org JSON-LD: {e}"))
    })?;

    let mut classes: Vec<SchemaOrgClass> = Vec::new();
    let mut properties: Vec<SchemaOrgProperty> = Vec::new();

    for node in raw.graph {
        let types: Vec<String> = node.node_type.into_vec();
        let is_class = types.iter().any(|t| t == "rdfs:Class");
        let is_property = types.iter().any(|t| t == "rdf:Property");

        // Skip enum values, datatypes, and documents — we only care about
        // "rdfs:Class" and "rdf:Property" nodes.
        if !is_class && !is_property {
            continue;
        }

        let Some(id) = node.id else {
            continue;
        };
        // Only keep nodes defined in the Schema.org namespace. External
        // namespaces (foaf, owl, rdfs, xsd, ...) appear as
        // `rdfs:subClassOf` references and shouldn't become seed schemas
        // themselves.
        let label = match node.label {
            Some(l) => l.into_string(),
            None => match id.strip_prefix("schema:") {
                Some(stripped) => stripped.to_string(),
                None => continue,
            },
        };
        if !id.starts_with("schema:") {
            continue;
        }

        let comment_text = node.comment.map(LabelField::into_string);

        if is_class {
            classes.push(SchemaOrgClass {
                label,
                comment: comment_text,
            });
        } else {
            let domain = node
                .domain_includes
                .into_vec()
                .into_iter()
                .filter_map(|r| r.id.strip_prefix("schema:").map(String::from))
                .collect();
            let range = node
                .range_includes
                .into_vec()
                .into_iter()
                .filter_map(|r| r.id.strip_prefix("schema:").map(String::from))
                .collect();
            properties.push(SchemaOrgProperty {
                label,
                comment: comment_text,
                domain_includes: domain,
                range_includes: range,
            });
        }
    }

    let mut properties_by_domain: HashMap<String, Vec<String>> = HashMap::new();
    for prop in &properties {
        for domain in &prop.domain_includes {
            properties_by_domain
                .entry(domain.clone())
                .or_default()
                .push(prop.label.clone());
        }
    }

    // Dedup each domain's property list — Schema.org occasionally lists the
    // same property under a class via multiple paths.
    for props in properties_by_domain.values_mut() {
        let seen: HashSet<String> = props.iter().cloned().collect();
        *props = seen.into_iter().collect();
        props.sort();
    }

    let property_by_snake_name: HashMap<String, SchemaOrgProperty> = properties
        .iter()
        .map(|p| (property_name_to_snake_case(&p.label), p.clone()))
        .collect();

    Ok(ParsedDump {
        classes,
        properties,
        properties_by_domain,
        property_by_snake_name,
    })
}

// ─────────────────────────────────────────────────────────────────────
//  Helpers
// ─────────────────────────────────────────────────────────────────────

/// Convert a Schema.org property name to the canonical-field snake_case
/// form used elsewhere in the schema service.
///
/// Examples:
///   `givenName` → `given_name`
///   `birthDate` → `birth_date`
///   `telephone` → `telephone`
///   `url` → `url`
///   `ISBN` → `isbn`
pub fn property_name_to_snake_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    let chars: Vec<char> = name.chars().collect();
    for (i, c) in chars.iter().enumerate() {
        if c.is_ascii_uppercase() {
            let prev_is_lower = i > 0 && chars[i - 1].is_ascii_lowercase();
            let next_is_lower = i + 1 < chars.len() && chars[i + 1].is_ascii_lowercase();
            let prev_is_upper = i > 0 && chars[i - 1].is_ascii_uppercase();
            // Insert underscore at camelCase boundary (prev lowercase) or
            // at the end of an acronym run (prev uppercase, next lowercase,
            // e.g. `URLPath` → `url_path`).
            if i > 0 && (prev_is_lower || (prev_is_upper && next_is_lower)) {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(*c);
        }
    }
    out
}

/// Map Schema.org `rangeIncludes` values to a `FieldValueType`. Schema.org
/// properties can have multiple ranges (`Person | Organization`); we
/// collapse to the most general scalar type since fold_db's structural
/// `OneOf` unions don't round-trip cleanly. `String` is the safe default
/// for unknown or object-typed ranges.
#[cfg(any(test, feature = "schema-org-seed-data"))]
fn infer_field_type_from_ranges(ranges: &[String]) -> FieldValueType {
    let has = |t: &str| ranges.iter().any(|r| r == t);

    if has("Integer") {
        FieldValueType::Integer
    } else if has("Number") || has("Float") {
        FieldValueType::Float
    } else if has("Boolean") {
        FieldValueType::Boolean
    } else {
        // Text, Date, DateTime, URL, Time, Duration, and any reference to
        // another Schema.org class all collapse to String. Losing
        // structural union information is an accepted trade-off in this
        // pass — see projects/schema-org-seeding in gbrain.
        FieldValueType::String
    }
}

// ─────────────────────────────────────────────────────────────────────
//  Tests
// ─────────────────────────────────────────────────────────────────────
